apiVersion: v1
kind: Namespace
metadata:
  name: test-orc1
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: test-orc1
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-container
<<<<<<< HEAD
    image: cgr.dev/chainguard/nginx
=======
    image: cgr.dev/chainguard/nginx:1.28
>>>>>>> 7f6b813 (commit updated yaml file)
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app.kubernetes.io/name: nginx-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
